package lt.vu.mybatis.dao;

import java.util.List;
import lt.vu.mybatis.model.Country;
import org.apache.ibatis.annotations.Param;
import org.mybatis.cdi.Mapper;

@Mapper
public interface CountryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table countries
     *
     * @mbg.generated Thu Apr 16 22:32:08 EEST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table countries
     *
     * @mbg.generated Thu Apr 16 22:32:08 EEST 2020
     */
    int insert(Country record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table countries
     *
     * @mbg.generated Thu Apr 16 22:32:08 EEST 2020
     */
    Country selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table countries
     *
     * @mbg.generated Thu Apr 16 22:32:08 EEST 2020
     */
    List<Country> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table countries
     *
     * @mbg.generated Thu Apr 16 22:32:08 EEST 2020
     */
    int updateByPrimaryKey(Country record);

    List<Country> selectUnusedCountries();

    List<Country> selectPlayerCountries(@Param("playerId") int playerId);
}