package lt.vu.mybatis.dao;

import java.util.List;
import lt.vu.mybatis.model.Map;
import org.apache.ibatis.annotations.Param;
import org.mybatis.cdi.Mapper;

@Mapper
public interface MapMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table map
     *
     * @mbg.generated Thu Apr 16 22:32:08 EEST 2020
     */
    int deleteByPrimaryKey(@Param("territoryId") Integer territoryId, @Param("territoryId1") Integer territoryId1);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table map
     *
     * @mbg.generated Thu Apr 16 22:32:08 EEST 2020
     */
    int insert(Map record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table map
     *
     * @mbg.generated Thu Apr 16 22:32:08 EEST 2020
     */
    List<Map> selectAll();
}