package lt.vu.mybatis.dao;

import java.util.List;
import lt.vu.mybatis.model.Player;
import org.mybatis.cdi.Mapper;

@Mapper
public interface PlayerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table players
     *
     * @mbg.generated Thu Apr 16 22:34:38 EEST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table players
     *
     * @mbg.generated Thu Apr 16 22:34:38 EEST 2020
     */
    int insert(Player record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table players
     *
     * @mbg.generated Thu Apr 16 22:34:38 EEST 2020
     */
    Player selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table players
     *
     * @mbg.generated Thu Apr 16 22:34:38 EEST 2020
     */
    List<Player> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table players
     *
     * @mbg.generated Thu Apr 16 22:34:38 EEST 2020
     */
    int updateByPrimaryKey(Player record);

    int setMoneyBack();
}