package lt.vu.mybatis.dao;

import java.util.List;
import lt.vu.mybatis.model.Territory;
import org.apache.ibatis.annotations.Param;
import org.mybatis.cdi.Mapper;

@Mapper
public interface TerritoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table territories
     *
     * @mbg.generated Thu Apr 16 22:32:08 EEST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table territories
     *
     * @mbg.generated Thu Apr 16 22:32:08 EEST 2020
     */
    int insert(Territory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table territories
     *
     * @mbg.generated Thu Apr 16 22:32:08 EEST 2020
     */
    Territory selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table territories
     *
     * @mbg.generated Thu Apr 16 22:32:08 EEST 2020
     */
    List<Territory> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table territories
     *
     * @mbg.generated Thu Apr 16 22:32:08 EEST 2020
     */
    int updateByPrimaryKey(Territory record);

    int updateByCountryPlayerId(@Param("countryId") int countryId, @Param("playerId") int playerId);

    List<Territory> selectByPlayer(@Param("playerId") int playerId);

    int unassignPlayerId(@Param("territoryId") int territoryId);

    List<Territory> selectFree();

    void assignPlayerId(@Param("territoryId") int territoryId, @Param("playerId") int playerId);

    List<Territory> selectNeighbours(@Param("territoryId") int territoryId, @Param("playerId") int playerId);

    List<Territory> selectByPlayerAndState(@Param("playerId") int playerId);

    int updateByState(@Param("state") int state, @Param("territoryId") int territoryId);
    int updateStateByPlayer(@Param("state") int state, @Param("playerId") int playerId);
}