package lt.vu.mybatis.model;

import java.util.Date;

public class Action {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column actions.id
     *
     * @mbg.generated Thu Apr 16 22:32:08 EEST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column actions.playerId
     *
     * @mbg.generated Thu Apr 16 22:32:08 EEST 2020
     */
    private Integer playerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column actions.priority
     *
     * @mbg.generated Thu Apr 16 22:32:08 EEST 2020
     */
    private Integer priority;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column actions.action
     *
     * @mbg.generated Thu Apr 16 22:32:08 EEST 2020
     */
    private String action;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column actions.territoryAId
     *
     * @mbg.generated Thu Apr 16 22:32:08 EEST 2020
     */
    private Integer territoryAId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column actions.territoryBId
     *
     * @mbg.generated Thu Apr 16 22:32:08 EEST 2020
     */
    private Integer territoryBId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column actions.creationDate
     *
     * @mbg.generated Thu Apr 16 22:32:08 EEST 2020
     */
    private Date creationDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column actions.roundNr
     *
     * @mbg.generated Thu Apr 16 22:32:08 EEST 2020
     */
    private Integer roundNr;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column actions.id
     *
     * @return the value of actions.id
     *
     * @mbg.generated Thu Apr 16 22:32:08 EEST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column actions.id
     *
     * @param id the value for actions.id
     *
     * @mbg.generated Thu Apr 16 22:32:08 EEST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column actions.playerId
     *
     * @return the value of actions.playerId
     *
     * @mbg.generated Thu Apr 16 22:32:08 EEST 2020
     */
    public Integer getPlayerId() {
        return playerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column actions.playerId
     *
     * @param playerId the value for actions.playerId
     *
     * @mbg.generated Thu Apr 16 22:32:08 EEST 2020
     */
    public void setPlayerId(Integer playerId) {
        this.playerId = playerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column actions.priority
     *
     * @return the value of actions.priority
     *
     * @mbg.generated Thu Apr 16 22:32:08 EEST 2020
     */
    public Integer getPriority() {
        return priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column actions.priority
     *
     * @param priority the value for actions.priority
     *
     * @mbg.generated Thu Apr 16 22:32:08 EEST 2020
     */
    public void setPriority(Integer priority) {
        this.priority = priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column actions.action
     *
     * @return the value of actions.action
     *
     * @mbg.generated Thu Apr 16 22:32:08 EEST 2020
     */
    public String getAction() {
        return action;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column actions.action
     *
     * @param action the value for actions.action
     *
     * @mbg.generated Thu Apr 16 22:32:08 EEST 2020
     */
    public void setAction(String action) {
        this.action = action;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column actions.territoryAId
     *
     * @return the value of actions.territoryAId
     *
     * @mbg.generated Thu Apr 16 22:32:08 EEST 2020
     */
    public Integer getTerritoryAId() {
        return territoryAId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column actions.territoryAId
     *
     * @param territoryAId the value for actions.territoryAId
     *
     * @mbg.generated Thu Apr 16 22:32:08 EEST 2020
     */
    public void setTerritoryAId(Integer territoryAId) {
        this.territoryAId = territoryAId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column actions.territoryBId
     *
     * @return the value of actions.territoryBId
     *
     * @mbg.generated Thu Apr 16 22:32:08 EEST 2020
     */
    public Integer getTerritoryBId() {
        return territoryBId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column actions.territoryBId
     *
     * @param territoryBId the value for actions.territoryBId
     *
     * @mbg.generated Thu Apr 16 22:32:08 EEST 2020
     */
    public void setTerritoryBId(Integer territoryBId) {
        this.territoryBId = territoryBId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column actions.creationDate
     *
     * @return the value of actions.creationDate
     *
     * @mbg.generated Thu Apr 16 22:32:08 EEST 2020
     */
    public Date getCreationDate() {
        return creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column actions.creationDate
     *
     * @param creationDate the value for actions.creationDate
     *
     * @mbg.generated Thu Apr 16 22:32:08 EEST 2020
     */
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column actions.roundNr
     *
     * @return the value of actions.roundNr
     *
     * @mbg.generated Thu Apr 16 22:32:08 EEST 2020
     */
    public Integer getRoundNr() {
        return roundNr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column actions.roundNr
     *
     * @param roundNr the value for actions.roundNr
     *
     * @mbg.generated Thu Apr 16 22:32:08 EEST 2020
     */
    public void setRoundNr(Integer roundNr) {
        this.roundNr = roundNr;
    }
}