package lt.vu.mybatis.model;

public class Map {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column map.territory_id
     *
     * @mbg.generated Thu Apr 16 22:32:08 EEST 2020
     */
    private Integer territoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column map.territory_id1
     *
     * @mbg.generated Thu Apr 16 22:32:08 EEST 2020
     */
    private Integer territoryId1;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column map.territory_id
     *
     * @return the value of map.territory_id
     *
     * @mbg.generated Thu Apr 16 22:32:08 EEST 2020
     */
    public Integer getTerritoryId() {
        return territoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column map.territory_id
     *
     * @param territoryId the value for map.territory_id
     *
     * @mbg.generated Thu Apr 16 22:32:08 EEST 2020
     */
    public void setTerritoryId(Integer territoryId) {
        this.territoryId = territoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column map.territory_id1
     *
     * @return the value of map.territory_id1
     *
     * @mbg.generated Thu Apr 16 22:32:08 EEST 2020
     */
    public Integer getTerritoryId1() {
        return territoryId1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column map.territory_id1
     *
     * @param territoryId1 the value for map.territory_id1
     *
     * @mbg.generated Thu Apr 16 22:32:08 EEST 2020
     */
    public void setTerritoryId1(Integer territoryId1) {
        this.territoryId1 = territoryId1;
    }
}