package lt.vu.mybatis.model;

public class Player {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column players.id
     *
     * @mbg.generated Thu Apr 16 22:34:38 EEST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column players.isAI
     *
     * @mbg.generated Thu Apr 16 22:34:38 EEST 2020
     */
    private Byte isai;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column players.name
     *
     * @mbg.generated Thu Apr 16 22:34:38 EEST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column players.money
     *
     * @mbg.generated Thu Apr 16 22:34:38 EEST 2020
     */
    private Integer money;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column players.password
     *
     * @mbg.generated Thu Apr 16 22:34:38 EEST 2020
     */
    private String password;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column players.id
     *
     * @return the value of players.id
     *
     * @mbg.generated Thu Apr 16 22:34:38 EEST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column players.id
     *
     * @param id the value for players.id
     *
     * @mbg.generated Thu Apr 16 22:34:38 EEST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column players.isAI
     *
     * @return the value of players.isAI
     *
     * @mbg.generated Thu Apr 16 22:34:38 EEST 2020
     */
    public Byte getIsai() {
        return isai;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column players.isAI
     *
     * @param isai the value for players.isAI
     *
     * @mbg.generated Thu Apr 16 22:34:38 EEST 2020
     */
    public void setIsai(Byte isai) {
        this.isai = isai;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column players.name
     *
     * @return the value of players.name
     *
     * @mbg.generated Thu Apr 16 22:34:38 EEST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column players.name
     *
     * @param name the value for players.name
     *
     * @mbg.generated Thu Apr 16 22:34:38 EEST 2020
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column players.money
     *
     * @return the value of players.money
     *
     * @mbg.generated Thu Apr 16 22:34:38 EEST 2020
     */
    public Integer getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column players.money
     *
     * @param money the value for players.money
     *
     * @mbg.generated Thu Apr 16 22:34:38 EEST 2020
     */
    public void setMoney(Integer money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column players.password
     *
     * @return the value of players.password
     *
     * @mbg.generated Thu Apr 16 22:34:38 EEST 2020
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column players.password
     *
     * @param password the value for players.password
     *
     * @mbg.generated Thu Apr 16 22:34:38 EEST 2020
     */
    public void setPassword(String password) {
        this.password = password;
    }
}