package lt.vu.mybatis.model;

public class Territory {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column territories.id
     *
     * @mbg.generated Thu Apr 16 22:32:08 EEST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column territories.type
     *
     * @mbg.generated Thu Apr 16 22:32:08 EEST 2020
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column territories.countryId
     *
     * @mbg.generated Thu Apr 16 22:32:08 EEST 2020
     */
    private Integer countryid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column territories.name
     *
     * @mbg.generated Thu Apr 16 22:32:08 EEST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column territories.state
     *
     * @mbg.generated Thu Apr 16 22:32:08 EEST 2020
     */
    private Integer state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column territories.playerId
     *
     * @mbg.generated Thu Apr 16 22:32:08 EEST 2020
     */
    private Integer playerid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column territories.id
     *
     * @return the value of territories.id
     *
     * @mbg.generated Thu Apr 16 22:32:08 EEST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column territories.id
     *
     * @param id the value for territories.id
     *
     * @mbg.generated Thu Apr 16 22:32:08 EEST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column territories.type
     *
     * @return the value of territories.type
     *
     * @mbg.generated Thu Apr 16 22:32:08 EEST 2020
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column territories.type
     *
     * @param type the value for territories.type
     *
     * @mbg.generated Thu Apr 16 22:32:08 EEST 2020
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column territories.countryId
     *
     * @return the value of territories.countryId
     *
     * @mbg.generated Thu Apr 16 22:32:08 EEST 2020
     */
    public Integer getCountryid() {
        return countryid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column territories.countryId
     *
     * @param countryid the value for territories.countryId
     *
     * @mbg.generated Thu Apr 16 22:32:08 EEST 2020
     */
    public void setCountryid(Integer countryid) {
        this.countryid = countryid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column territories.name
     *
     * @return the value of territories.name
     *
     * @mbg.generated Thu Apr 16 22:32:08 EEST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column territories.name
     *
     * @param name the value for territories.name
     *
     * @mbg.generated Thu Apr 16 22:32:08 EEST 2020
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column territories.state
     *
     * @return the value of territories.state
     *
     * @mbg.generated Thu Apr 16 22:32:08 EEST 2020
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column territories.state
     *
     * @param state the value for territories.state
     *
     * @mbg.generated Thu Apr 16 22:32:08 EEST 2020
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column territories.playerId
     *
     * @return the value of territories.playerId
     *
     * @mbg.generated Thu Apr 16 22:32:08 EEST 2020
     */
    public Integer getPlayerid() {
        return playerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column territories.playerId
     *
     * @param playerid the value for territories.playerId
     *
     * @mbg.generated Thu Apr 16 22:32:08 EEST 2020
     */
    public void setPlayerid(Integer playerid) {
        this.playerid = playerid;
    }
}